/**
 * A classroom generated by `POST /api/generate-classroom` on PostgreSQL: the
 * finished course is saved once into the job owner's library, complete, and
 * every generated image and narration clip is an asset-pool entry of that
 * owner, committed by the course write. The LLM and the media providers are
 * mocked; the document store, the asset pool and the ownership rows are real.
 */
import { Pool } from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';

import { validateAppScene, validateAppStage } from '@/lib/document-store/validators';
import { createOwnerBoundDocumentStore } from '@/lib/persistence/owner-bound-document-store';
import { getServerPersistenceProvider } from '@/lib/persistence/server-provider';
import { saveCompletedClassroom, saveGeneratedClassroom } from '@/lib/server/classroom-persistence';

const mocks = vi.hoisted(() => ({
  generateSceneOutlinesFromRequirements: vi.fn(),
  generateSceneContent: vi.fn(),
  generateSceneActions: vi.fn(),
  generateImage: vi.fn(),
  generateTTS: vi.fn(),
}));

vi.mock('@/lib/server/resolve-model', () => ({
  resolveModel: vi.fn(async () => ({
    model: { id: 'language-model' },
    modelInfo: {},
    modelString: 'test:model',
    providerId: 'test',
    apiKey: '',
    serverManaged: true,
  })),
}));

vi.mock('@/lib/ai/providers', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/lib/ai/providers')>()),
  isProviderKeyRequired: () => false,
}));

vi.mock('@/lib/ai/llm', () => ({ callLLM: vi.fn(async () => ({ text: 'ok' })) }));

vi.mock('@openmaic/generation', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@openmaic/generation')>()),
  generateSceneOutlinesFromRequirements: mocks.generateSceneOutlinesFromRequirements,
  applyOutlineFallbacks: (value: unknown) => value,
  generateSceneContent: mocks.generateSceneContent,
  generateSceneActions: mocks.generateSceneActions,
}));

vi.mock('@/lib/server/provider-config', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/lib/server/provider-config')>()),
  getServerImageProviders: () => ({ seedream: {} }),
  getServerVideoProviders: () => ({}),
  getServerTTSProviders: () => ({ 'openai-tts': {} }),
  resolveImageApiKey: () => 'image-key',
  resolveImageModel: () => 'image-model',
  resolveTTSApiKey: () => 'tts-key',
}));

vi.mock('@/lib/server/generation-capabilities', () => ({
  resolveServerGenerationCapabilities: () => ({
    webSearch: false,
    imageGeneration: true,
    videoGeneration: false,
    tts: true,
  }),
}));

vi.mock('@/lib/media/image-providers', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/lib/media/image-providers')>()),
  generateImage: mocks.generateImage,
}));

vi.mock('@/lib/audio/tts-providers', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/lib/audio/tts-providers')>()),
  generateTTS: mocks.generateTTS,
}));

vi.mock('@/lib/server/scene-generation', () => ({
  createSceneWithActions: (
    outline: { type: string; title: string; order: number },
    content: { elements: unknown[] },
    actions: unknown[],
    api: {
      scene: { create: (scene: unknown) => { success: boolean; data?: string } };
    },
  ) => {
    const result = api.scene.create({
      type: outline.type,
      title: outline.title,
      order: outline.order,
      content: {
        type: 'slide',
        canvas: {
          id: 'slide-1',
          viewportSize: 1000,
          viewportRatio: 0.5625,
          theme: {
            backgroundColor: '#fff',
            themeColors: ['#000'],
            fontColor: '#000',
            fontName: 'Inter',
          },
          elements: content.elements,
        },
      },
      actions,
    });
    return result.success ? (result.data ?? null) : null;
  },
}));

const contractUrl = process.env.PG_CONTRACT_URL;
const TEST_SCHEMA = 'openmaic_classroom_generation_test';
const OWNER = 'user:teacher';
const OTHER = 'user:visitor';
const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3]);
const CLIP = new Uint8Array([9, 8, 7, 6]);

const outline = {
  id: 'outline-1',
  type: 'slide',
  title: 'Photosynthesis',
  description: 'How plants make food',
  keyPoints: ['Light'],
  order: 1,
  mediaGenerations: [{ type: 'image', prompt: 'a leaf', elementId: 'gen_img_leaf' }],
};

describe.skipIf(!contractUrl)('generated classroom persistence on PostgreSQL', () => {
  let admin: Pool;
  let pool: Pool;
  const previousEnv = {
    DATABASE_URL: process.env.DATABASE_URL,
    ASSET_S3_BUCKET: process.env.ASSET_S3_BUCKET,
  };

  beforeAll(async () => {
    admin = new Pool({ connectionString: contractUrl });
    await admin.query(`DROP SCHEMA IF EXISTS ${TEST_SCHEMA} CASCADE`);
    await admin.query(`CREATE SCHEMA ${TEST_SCHEMA}`);
    pool = new Pool({ connectionString: contractUrl, options: `-c search_path=${TEST_SCHEMA}` });
    const databaseUrl = `${contractUrl}${contractUrl!.includes('?') ? '&' : '?'}application_name=classroom-generation`;
    process.env.DATABASE_URL = databaseUrl;
    process.env.ASSET_S3_BUCKET = '';
    await getServerPersistenceProvider(databaseUrl, () => pool);
  });

  beforeEach(async () => {
    // The media the job generates comes from the deployment's slots.
    (await import('@/lib/server/model-config/runtime')).setDeploymentConfigForTests({
      layer: {
        source: 'deployment',
        config: {
          providers: {
            img: { preset: 'seedream', apiKey: 'image-key' },
            voice: { preset: 'openai-tts', apiKey: 'tts-key' },
          },
          slots: { image: 'img:image-model', tts: 'voice', video: null },
        },
      },
      defaults: null,
      notices: [],
    });
    for (const mock of Object.values(mocks)) mock.mockReset();
    mocks.generateSceneOutlinesFromRequirements.mockResolvedValue({
      success: true,
      data: { languageDirective: 'Use English.', courseTitle: 'Plants', outlines: [outline] },
    });
    mocks.generateSceneContent.mockResolvedValue({
      elements: [
        {
          id: 'leaf-image',
          type: 'image',
          src: 'gen_img_leaf',
          left: 0,
          top: 0,
          width: 400,
          height: 300,
          rotate: 0,
          fixedRatio: true,
        },
      ],
    });
    mocks.generateSceneActions.mockResolvedValue([
      { id: 'speech-1', type: 'speech', text: 'Plants turn light into sugar.' },
    ]);
    mocks.generateImage.mockResolvedValue({
      base64: PNG.toString('base64'),
      mimeType: 'image/png',
    });
    mocks.generateTTS.mockResolvedValue({ audio: CLIP, format: 'mp3' });
  });

  afterAll(async () => {
    for (const [name, value] of Object.entries(previousEnv)) {
      if (value === undefined) delete process.env[name];
      else process.env[name] = value;
    }
    await pool.end();
    await admin.query(`DROP SCHEMA IF EXISTS ${TEST_SCHEMA} CASCADE`);
    await admin.end();
  });

  function store(ownerId: string) {
    return createOwnerBoundDocumentStore({
      pool,
      ownerId,
      validateScene: validateAppScene,
      validateStage: validateAppStage,
    });
  }

  it("saves the course complete into the owner's library, with its media in the owner's pool", async () => {
    const { generateClassroom } = await import('@/lib/server/classroom-generation');
    const result = await generateClassroom(
      { requirement: 'Teach photosynthesis' },
      { baseUrl: 'https://openmaic.example', ownerId: OWNER },
    );

    expect(result.url).toBe(`https://openmaic.example/classroom/${result.id}`);
    expect(result.ttsCoverage).toEqual({ written: 1, total: 1 });
    expect(result.warning).toBeUndefined();

    // The owner's library lists it; another owner's does not, but may read it by id.
    expect((await store(OWNER).listDocuments()).map((doc) => doc.id)).toContain(result.id);
    expect((await store(OTHER).listDocuments()).map((doc) => doc.id)).not.toContain(result.id);
    const document = await store(OTHER).loadDocument(result.id);
    expect(document?.stage.name).toBe('Plants');
    expect(document?.outline).toMatchObject({ generationComplete: true, outlines: [outline] });

    const meta = await pool.query(
      'SELECT owner_id, generation_complete FROM stage_meta WHERE stage_id = $1',
      [result.id],
    );
    expect(meta.rows).toEqual([{ owner_id: OWNER, generation_complete: true }]);

    // The image and the narration are allocated ids, not URLs or files.
    const scene = document!.scenes[0]!;
    const image = (scene.content as { canvas: { elements: Array<{ src: string }> } }).canvas
      .elements[0]!;
    const speech = scene.actions![0] as { audioId?: string; audioUrl?: string };
    expect(image.src).toMatch(/^ast_/);
    expect(speech.audioId).toMatch(/^ast_/);
    expect(speech).not.toHaveProperty('audioUrl');

    // Both entries are the owner's, committed and referenced by the course.
    const entries = await pool.query(
      `SELECT e.id, e.principal, e.mime, e.committed_at IS NOT NULL AS committed,
              EXISTS (SELECT 1 FROM document_asset_refs r
                       WHERE r.asset_id = e.id AND r.stage_id = $1) AS referenced
         FROM asset_entries e WHERE e.id = ANY($2) ORDER BY e.mime`,
      [result.id, [image.src, speech.audioId]],
    );
    expect(entries.rows).toEqual([
      {
        id: speech.audioId,
        principal: `owner:${OWNER}`,
        mime: 'audio/mpeg',
        committed: true,
        referenced: true,
      },
      {
        id: image.src,
        principal: `owner:${OWNER}`,
        mime: 'image/png',
        committed: true,
        referenced: true,
      },
    ]);
  });

  function shell(id: string, name: string) {
    return { stage: { id, name, createdAt: 1, updatedAt: 1 }, scenes: [], outlines: [] };
  }

  it("never replaces a course that holds the id, the owner's own or another's", async () => {
    await store(OWNER).saveDocument({ stage: shell('stage-own', 'Mine').stage, scenes: [] });
    await store(OTHER).saveDocument({ stage: shell('stage-theirs', 'Theirs').stage, scenes: [] });

    for (const id of ['stage-own', 'stage-theirs']) {
      await expect(saveCompletedClassroom(OWNER, shell(id, 'Generated'))).rejects.toMatchObject({
        code: 'STAGE_ID_TAKEN',
      });
    }
    expect((await store(OWNER).loadDocument('stage-own'))?.stage.name).toBe('Mine');
    expect((await store(OTHER).loadDocument('stage-theirs'))?.stage.name).toBe('Theirs');
  });

  it('refuses a deleted id and a document row without ownership', async () => {
    const owned = store(OWNER);
    await owned.saveDocument({ stage: shell('stage-deleted', 'Gone').stage, scenes: [] });
    await owned.deleteDocument('stage-deleted');
    await pool.query(
      `INSERT INTO document_stages (id, name, data, created_at, updated_at)
       VALUES ('stage-orphan', 'Orphan', '{}'::jsonb, 1, 1)`,
    );

    for (const id of ['stage-deleted', 'stage-orphan']) {
      await expect(owned.createDocument(shell(id, 'New'))).rejects.toMatchObject({
        code: 'STAGE_ID_TAKEN',
      });
    }
    const meta = await pool.query('SELECT 1 FROM stage_meta WHERE stage_id = $1', ['stage-orphan']);
    expect(meta.rows).toEqual([]);
  });

  it('rolls back the course, its ownership and the extra rows when inTransaction throws', async () => {
    await pool.query('CREATE TABLE IF NOT EXISTS extra_rows (stage_id TEXT)');
    await expect(
      store(OWNER).createDocument(shell('stage-rolled-back', 'Rolled back'), {
        inTransaction: async (tx) => {
          await tx.query("INSERT INTO extra_rows (stage_id) VALUES ('stage-rolled-back')");
          throw new Error('ledger write failed');
        },
      }),
    ).rejects.toThrow('ledger write failed');

    for (const sql of [
      "SELECT 1 FROM document_stages WHERE id = 'stage-rolled-back'",
      "SELECT 1 FROM stage_meta WHERE stage_id = 'stage-rolled-back'",
      "SELECT 1 FROM extra_rows WHERE stage_id = 'stage-rolled-back'",
    ]) {
      expect((await pool.query(sql)).rows).toEqual([]);
    }
  });

  it('moves a generated classroom to a fresh id when its id is taken', async () => {
    await store(OTHER).saveDocument({ stage: shell('stage-taken', 'Theirs').stage, scenes: [] });

    const saved = await saveGeneratedClassroom(OWNER, shell('stage-taken', 'Generated'));

    expect(saved.stage.id).not.toBe('stage-taken');
    expect((await store(OWNER).loadDocument(saved.stage.id))?.stage.name).toBe('Generated');
    expect((await store(OTHER).loadDocument('stage-taken'))?.stage.name).toBe('Theirs');
  });

  it('writes no course when generation fails', async () => {
    mocks.generateSceneOutlinesFromRequirements.mockResolvedValue({
      success: true,
      data: { languageDirective: 'Use English.', outlines: [] },
    });
    const before = await pool.query('SELECT COUNT(*)::int AS n FROM document_stages');

    const { generateClassroom } = await import('@/lib/server/classroom-generation');
    await expect(
      generateClassroom(
        { requirement: 'Teach photosynthesis' },
        { baseUrl: 'https://openmaic.example', ownerId: OWNER },
      ),
    ).rejects.toThrow('No scenes were generated');

    const after = await pool.query('SELECT COUNT(*)::int AS n FROM document_stages');
    expect(after.rows[0].n).toBe(before.rows[0].n);
  });
});
