import { afterEach, describe, expect, test, vi } from 'vitest';
import { replaceMediaPlaceholders } from '@/lib/server/classroom-media-generation';
import type { Scene } from '@/lib/types/stage';
import type { SceneOutline } from '@/lib/types/generation';

// Generated bytes go to the asset pool; answer each allocation with an id
// that says what was stored, so the tests can read the type back off it.
const storeGeneratedAsset = vi.hoisted(() =>
  vi.fn(async (input: { ownerId: string; stageId: string; mimeType: string; kind: string }) => ({
    status: 'stored' as const,
    assetId: `ast_${input.ownerId}_${input.stageId}_${input.kind}_${input.mimeType}`,
  })),
);
vi.mock('@/lib/server/store-generated-asset', () => ({ storeGeneratedAsset }));

vi.mock('@/lib/server/provider-fetch', () => ({
  providerFetch: vi.fn(async (input: string | URL, init?: RequestInit) => {
    return fetch(input, init);
  }),
}));

vi.mock('@/lib/server/ssrf-guard', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/lib/server/ssrf-guard')>();
  return {
    ...actual,
    validateUrlForSSRFWithPolicy: vi.fn().mockResolvedValue(null),
  };
});

function slideScene(
  elements: Array<{ id: string; type: string; src?: string; mediaRef?: string }>,
) {
  return {
    id: 'scene_1',
    stageId: 'stage_1',
    type: 'slide',
    title: 'Scene',
    order: 1,
    content: {
      type: 'slide',
      canvas: {
        id: 'canvas_1',
        elements,
      },
    },
  } as unknown as Scene;
}

describe('classroom media placeholder replacement', () => {
  test('preserves direct video src when mediaRef is also present', () => {
    const scene = slideScene([
      {
        id: 'video_1',
        type: 'video',
        src: 'https://example.com/direct.mp4',
        mediaRef: 'gen_vid_real123',
      },
    ]);

    replaceMediaPlaceholders([scene], {
      gen_vid_real123: 'https://cdn.example.com/generated.mp4',
    });

    const content = scene.content as {
      canvas: { elements: Array<{ src?: string }> };
    };
    const video = content.canvas.elements[0];
    expect(video.src).toBe('https://example.com/direct.mp4');
  });

  test('preserves an author-supplied non-URL src when mediaRef is also present', () => {
    const scene = slideScene([
      {
        id: 'video_1',
        type: 'video',
        src: 'lesson-intro.mp4',
        mediaRef: 'gen_vid_real123',
      },
    ]);

    replaceMediaPlaceholders([scene], {
      gen_vid_real123: 'https://cdn.example.com/generated.mp4',
    });

    const content = scene.content as {
      canvas: { elements: Array<{ src?: string }> };
    };
    expect(content.canvas.elements[0].src).toBe('lesson-intro.mp4');
  });

  test('moves a generated video placeholder in src and mediaRef to the allocated id', () => {
    const scene = slideScene([
      { id: 'video_1', type: 'video', src: 'gen_vid_real123', mediaRef: 'gen_vid_real123' },
      { id: 'image_1', type: 'image', src: 'gen_img_real456' },
    ]);

    replaceMediaPlaceholders([scene], {
      gen_vid_real123: 'ast_video',
      gen_img_real456: 'ast_image',
    });

    const content = scene.content as {
      canvas: { elements: Array<{ src?: string; mediaRef?: string }> };
    };
    expect(content.canvas.elements[0]).toMatchObject({ src: 'ast_video', mediaRef: 'ast_video' });
    expect(content.canvas.elements[1]).toMatchObject({ src: 'ast_image' });
  });

  test('does not treat an image placeholder as the video-manifest overwrite guard', () => {
    const scene = slideScene([
      {
        id: 'video_1',
        type: 'video',
        src: 'gen_img_preview123',
        mediaRef: 'gen_vid_real123',
      },
    ]);

    replaceMediaPlaceholders([scene], {
      gen_vid_real123: 'https://cdn.example.com/generated.mp4',
    });

    const content = scene.content as {
      canvas: { elements: Array<{ src?: string }> };
    };
    expect(content.canvas.elements[0].src).toBe('gen_img_preview123');
  });
});

describe('generateMediaForClassroom model fallback', () => {
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.unstubAllGlobals();
    vi.useRealTimers();
  });

  test('gracefully skips media when every configured provider is force-disabled', async () => {
    // The generic key enables OpenAI's image fallback. This test owns only the
    // explicitly force-disabled providers below, so keep shell credentials out
    // of its provider set (and out of fetch-mock failure output).
    vi.stubEnv('OPENAI_API_KEY', '');
    vi.stubEnv('IMAGE_SEEDREAM_API_KEY', 'sk-seedream');
    vi.stubEnv('IMAGE_SEEDREAM_ENABLED', 'false');
    vi.stubEnv('VIDEO_SEEDANCE_API_KEY', 'sk-seedance');
    vi.stubEnv('VIDEO_SEEDANCE_ENABLED', 'false');
    vi.resetModules();

    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');
    const outlines = [
      {
        id: 'outline_disabled',
        type: 'slide',
        title: 'Scene',
        description: 'd',
        order: 1,
        mediaGenerations: [
          { type: 'image', prompt: 'image', elementId: 'gen_img_disabled' },
          { type: 'video', prompt: 'video', elementId: 'gen_vid_disabled' },
        ],
      },
    ] as unknown as SceneOutline[];

    await expect(generateMediaForClassroom(outlines, 'cls-disabled', 'owner-1')).resolves.toEqual({
      assets: {},
      storageFull: { images: false, video: false },
    });
    expect(fetchMock).not.toHaveBeenCalled();
  });

  test('falls back to the first catalog image model when the server pins no models', async () => {
    // Key-only managed provider (no IMAGE_SEEDREAM_MODELS pin): the resolver
    // yields no model, so the classroom path must fall back to the first
    // catalog model instead of reaching the adapter with an undefined model.
    vi.stubEnv('IMAGE_SEEDREAM_API_KEY', 'sk-seedream');
    vi.resetModules();

    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: [{ url: 'https://cdn.example.com/x.png' }] }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: { get: () => null },
        arrayBuffer: async () => new ArrayBuffer(8),
      });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');

    const outlines = [
      {
        id: 'outline_1',
        type: 'slide',
        title: 'Scene 1',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'image', prompt: 'a cat', elementId: 'gen_img_1' }],
      },
    ] as unknown as SceneOutline[];

    const mediaMap = await generateMediaForClassroom(outlines, 'cls-fallback', 'owner-1');

    expect(mediaMap.assets['gen_img_1']).toBe('ast_owner-1_cls-fallback_image_image/png');
    const genBody = JSON.parse(fetchMock.mock.calls[0][1].body);
    expect(genBody.model).toBe('doubao-seedream-5-0-260128');
  });

  test('uses the server-pinned model when IMAGE_<PREFIX>_MODELS is set', async () => {
    vi.stubEnv('IMAGE_SEEDREAM_API_KEY', 'sk-seedream');
    vi.stubEnv('IMAGE_SEEDREAM_MODELS', 'pinned-a');
    vi.resetModules();

    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: [{ url: 'https://cdn.example.com/y.png' }] }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: { get: () => null },
        arrayBuffer: async () => new ArrayBuffer(8),
      });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');

    const outlines = [
      {
        id: 'outline_1',
        type: 'slide',
        title: 'Scene 1',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'image', prompt: 'a cat', elementId: 'gen_img_2' }],
      },
    ] as unknown as SceneOutline[];

    await generateMediaForClassroom(outlines, 'cls-pinned', 'owner-1');

    const genBody = JSON.parse(fetchMock.mock.calls[0][1].body);
    expect(genBody.model).toBe('pinned-a');
  });

  test('normalizes GPT Image 2 classroom media to an accepted landscape size', async () => {
    vi.stubEnv('IMAGE_OPENAI_API_KEY', 'sk-openai');
    vi.stubEnv('IMAGE_OPENAI_MODELS', 'gpt-image-2');
    vi.resetModules();

    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: [{ url: 'https://cdn.example.com/gpt-image-2.png' }] }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: { get: () => null },
        arrayBuffer: async () => new ArrayBuffer(8),
      });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');
    const outlines = [
      {
        id: 'outline_gpt_image_2',
        type: 'slide',
        title: 'Scene',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'image', prompt: 'a plant', elementId: 'gen_img_gpt_image_2' }],
      },
    ] as unknown as SceneOutline[];

    await generateMediaForClassroom(outlines, 'cls-gpt-image-2', 'owner-1');

    const genBody = JSON.parse(fetchMock.mock.calls[0][1].body);
    expect(genBody).toMatchObject({ model: 'gpt-image-2', size: '1536x1024' });
  });

  test('falls back to the first catalog video model when the server pins no models', async () => {
    // Key-only managed provider (no VIDEO_SEEDANCE_MODELS pin): the resolver
    // yields no model, so the classroom path must fall back to the first
    // catalog model instead of reaching the adapter with an undefined model.
    vi.stubEnv('VIDEO_SEEDANCE_API_KEY', 'sk-seedance');
    vi.useFakeTimers();
    vi.resetModules();

    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => ({ id: 'video-task-1' }) })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          id: 'video-task-1',
          status: 'succeeded',
          content: { video_url: 'https://cdn.example.com/video.mp4' },
          resolution: '720p',
          ratio: '16:9',
          duration: 5,
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: { get: () => null },
        arrayBuffer: async () => new ArrayBuffer(8),
      });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');

    const outlines = [
      {
        id: 'outline_1',
        type: 'slide',
        title: 'Scene 1',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'video', prompt: 'a cat running', elementId: 'gen_vid_1' }],
      },
    ] as unknown as SceneOutline[];

    const mediaMapPromise = generateMediaForClassroom(outlines, 'cls-video-fallback', 'owner-1');
    // Seedance submits a task then polls on a 5s interval; advance the fake
    // timers past the first poll so the mocked success response is consumed.
    await vi.advanceTimersByTimeAsync(5_000);
    const mediaMap = await mediaMapPromise;

    expect(mediaMap.assets['gen_vid_1']).toBe('ast_owner-1_cls-video-fallback_video_video/mp4');
    const genBody = JSON.parse(fetchMock.mock.calls[0][1].body);
    expect(genBody.model).toBe('doubao-seedance-2-0-260128');
  });

  test('uses the server-pinned video model when VIDEO_<PREFIX>_MODELS is set', async () => {
    vi.stubEnv('VIDEO_SEEDANCE_API_KEY', 'sk-seedance');
    vi.stubEnv('VIDEO_SEEDANCE_MODELS', 'pinned-video-a');
    vi.useFakeTimers();
    vi.resetModules();

    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => ({ id: 'video-task-2' }) })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          id: 'video-task-2',
          status: 'succeeded',
          content: { video_url: 'https://cdn.example.com/video.mp4' },
          resolution: '720p',
          ratio: '16:9',
          duration: 5,
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        headers: { get: () => null },
        arrayBuffer: async () => new ArrayBuffer(8),
      });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');

    const outlines = [
      {
        id: 'outline_1',
        type: 'slide',
        title: 'Scene 1',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'video', prompt: 'a cat running', elementId: 'gen_vid_2' }],
      },
    ] as unknown as SceneOutline[];

    const mediaMapPromise = generateMediaForClassroom(outlines, 'cls-video-pinned', 'owner-1');
    await vi.advanceTimersByTimeAsync(5_000);
    const mediaMap = await mediaMapPromise;

    expect(mediaMap.assets['gen_vid_2']).toBe('ast_owner-1_cls-video-pinned_video_video/mp4');
    const genBody = JSON.parse(fetchMock.mock.calls[0][1].body);
    expect(genBody.model).toBe('pinned-video-a');
  });

  test('stores Grok inline bytes under the type it reported', async () => {
    // xAI answers `b64_json` with JPEG bytes and declares no media type of its
    // own, so the adapter reports one. Recording it as `image/png` — which this
    // path once did for every inline image — serves the bytes as the wrong type.
    // The generic key is cleared for the same reason the first test clears it:
    // it would otherwise enable OpenAI's image fallback alongside Grok's.
    vi.stubEnv('OPENAI_API_KEY', '');
    vi.stubEnv('IMAGE_GROK_API_KEY', 'sk-grok');
    vi.resetModules();

    const jpegBase64 = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10]).toString('base64');
    const fetchMock = vi.fn().mockResolvedValueOnce({
      ok: true,
      json: async () => ({ data: [{ b64_json: jpegBase64 }] }),
    });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');

    const outlines = [
      {
        id: 'outline_1',
        type: 'slide',
        title: 'Scene 1',
        description: 'd',
        order: 1,
        mediaGenerations: [{ type: 'image', prompt: 'a cat', elementId: 'gen_img_grok' }],
      },
    ] as unknown as SceneOutline[];

    const mediaMap = await generateMediaForClassroom(outlines, 'cls-grok', 'owner-1');

    expect(mediaMap.assets['gen_img_grok']).toBe('ast_owner-1_cls-grok_image_image/jpeg');
  });

  test('stops only the phase the asset store refused', async () => {
    vi.stubEnv('OPENAI_API_KEY', '');
    vi.stubEnv('IMAGE_GROK_API_KEY', 'sk-grok');
    vi.stubEnv('VIDEO_SEEDANCE_API_KEY', 'sk-seedance');
    vi.useFakeTimers();
    vi.resetModules();
    // The video is refused; the images still fit.
    storeGeneratedAsset.mockClear();
    storeGeneratedAsset.mockImplementation(async (input) =>
      input.kind === 'video'
        ? ({ status: 'refused', reason: 'storage-full' } as never)
        : { status: 'stored' as const, assetId: `ast_${input.stageId}_${input.kind}` },
    );

    const fetchMock = vi.fn(async (input: string | URL) => {
      const url = String(input);
      if (url.includes('x.ai')) {
        return {
          ok: true,
          json: async () => ({ data: [{ b64_json: Buffer.from([1, 2, 3]).toString('base64') }] }),
        };
      }
      if (url.includes('/tasks/')) {
        return {
          ok: true,
          json: async () => ({
            id: 'video-task',
            status: 'succeeded',
            content: { video_url: 'https://cdn.example.com/video.mp4' },
          }),
        };
      }
      if (url.includes('cdn.example.com')) {
        return {
          ok: true,
          headers: { get: () => null },
          arrayBuffer: async () => new ArrayBuffer(8),
        };
      }
      return { ok: true, json: async () => ({ id: 'video-task' }) };
    });
    vi.stubGlobal('fetch', fetchMock);

    const { generateMediaForClassroom } = await import('@/lib/server/classroom-media-generation');
    const outlines = [
      {
        id: 'outline_full',
        type: 'slide',
        title: 'Scene',
        description: 'd',
        order: 1,
        mediaGenerations: [
          { type: 'video', prompt: 'a river', elementId: 'gen_vid_big' },
          { type: 'video', prompt: 'a lake', elementId: 'gen_vid_after' },
          { type: 'image', prompt: 'a cat', elementId: 'gen_img_a' },
          { type: 'image', prompt: 'a dog', elementId: 'gen_img_b' },
        ],
      },
    ] as unknown as SceneOutline[];

    const pending = generateMediaForClassroom(outlines, 'cls-full', 'owner-1');
    await vi.advanceTimersByTimeAsync(30_000);
    const result = await pending;

    expect(result.storageFull).toEqual({ images: false, video: true });
    expect(result.assets).toEqual({
      gen_img_a: 'ast_cls-full_image',
      gen_img_b: 'ast_cls-full_image',
    });
    // The second video is never requested from its provider.
    const videoSubmissions = storeGeneratedAsset.mock.calls.filter(
      ([input]) => input.kind === 'video',
    );
    expect(videoSubmissions).toHaveLength(1);
    storeGeneratedAsset.mockReset();
  });
});
