/**
 * Server-side media and TTS generation for classrooms.
 *
 * Generates images, videos and TTS audio for a classroom and stores the bytes
 * in the asset pool for the classroom's owner. The scenes then name the
 * allocated ids, exactly like a course generated in the browser; the document
 * write that saves them commits the allocations
 * (`lib/server/store-generated-asset.ts`).
 */

import path from 'path';
import { createLogger } from '@/lib/logger';
import { classroomMediaMimeType } from '@/lib/server/classroom-storage';
import { storeGeneratedAsset, type GeneratedAssetKind } from '@/lib/server/store-generated-asset';
import { generateImage } from '@/lib/media/image-providers';
import { generateVideo, normalizeVideoOptions } from '@/lib/media/video-providers';
import {
  managedMediaDownloadFetch,
  managedMediaProviderFetch,
  mediaDownloadFetch,
  mediaProviderFetch,
} from '@/lib/server/media-provider-fetch';
import { generateTTS, TTSRateLimitError } from '@/lib/audio/tts-providers';
import { DEFAULT_TTS_VOICES, DEFAULT_TTS_MODELS, TTS_PROVIDERS } from '@/lib/audio/constants';
import { IMAGE_PROVIDERS } from '@/lib/media/image-providers';
import { VIDEO_PROVIDERS } from '@/lib/media/video-providers';
import { adapterOptions } from '@/lib/server/model-config/adapter-options';
import { serverMediaConnection } from '@/lib/server/model-config/media';
import type { SceneOutline } from '@/lib/types/generation';
import type { Scene } from '@/lib/types/stage';
import type { SpeechAction } from '@/lib/types/action';
import type { ImageProviderId } from '@/lib/media/types';
import type { VideoProviderId } from '@/lib/media/types';
import type { TTSProviderId } from '@/lib/audio/types';
import { splitLongSpeechActions } from '@/lib/audio/tts-utils';
import { rewriteSceneMediaReference } from '@/lib/media/generated-media-references';
import { resolveImageSize } from '@/lib/server/image-sizing';
import { VOXCPM_AUTO_VOICE_ID, VOXCPM_TTS_PROVIDER_ID } from '@/lib/audio/voxcpm';
import { decodeDataUrl, fetchProviderResultUrl } from '@/lib/server/provider-result-fetch';

const log = createLogger('ClassroomMedia');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const DOWNLOAD_TIMEOUT_MS = 120_000; // 2 minutes
export const DOWNLOAD_MAX_SIZE = 100 * 1024 * 1024; // 100 MB

/**
 * The image types this path stores. The type rides the asset entry and is
 * what the bytes are served back as, so it has to follow what the adapter
 * reported rather than a constant. Anything unlisted is stored as `image/png`,
 * the type this path always assumed for inline images.
 */
const STORED_IMAGE_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp']);

function storedImageType(mime: string | undefined): string {
  return mime && STORED_IMAGE_TYPES.has(mime) ? mime : 'image/png';
}

export async function downloadToBuffer(url: string): Promise<Buffer> {
  if (url.startsWith('data:')) {
    return decodeDataUrl(url, DOWNLOAD_MAX_SIZE).bytes;
  }

  const resp = await fetchProviderResultUrl(url, {
    signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
    maxBytes: DOWNLOAD_MAX_SIZE,
  });
  if (!resp.ok) throw new Error(`Download failed: ${resp.status} ${resp.statusText}`);

  const contentLength = Number(resp.headers.get('content-length') || 0);
  if (contentLength > DOWNLOAD_MAX_SIZE) {
    throw new Error(`File too large: ${contentLength} bytes (max ${DOWNLOAD_MAX_SIZE})`);
  }

  const body = resp.body;
  if (!body) {
    const buf = Buffer.from(await resp.arrayBuffer());
    if (buf.byteLength > DOWNLOAD_MAX_SIZE) {
      throw new Error(`File too large: ${buf.byteLength} bytes (max ${DOWNLOAD_MAX_SIZE})`);
    }
    return buf;
  }

  const reader = body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      if (!value) continue;
      total += value.byteLength;
      if (total > DOWNLOAD_MAX_SIZE) {
        throw new Error(`File too large: ${total} bytes (max ${DOWNLOAD_MAX_SIZE})`);
      }
      chunks.push(value);
    }
    return Buffer.concat(chunks);
  } catch (error) {
    await reader.cancel().catch(() => undefined);
    throw error;
  } finally {
    reader.releaseLock?.();
  }
}

/**
 * Store generated bytes for the classroom's owner and answer the allocated id,
 * or `null` when the pool has no room. A caller that gets `null` stops its
 * phase (images, video or narration): later items of that kind would most
 * likely be refused too, after a paid provider call. The other phases go on,
 * because their items may be small enough to fit.
 */
async function storeClassroomAsset(
  ownerId: string,
  classroomId: string,
  bytes: Uint8Array,
  mimeType: string,
  kind: GeneratedAssetKind,
  label: string,
): Promise<string | null> {
  const stored = await storeGeneratedAsset({
    ownerId,
    stageId: classroomId,
    bytes,
    mimeType,
    kind,
  });
  if (stored.status === 'refused') {
    log.warn(`Asset storage is full; ${label} was not stored and the phase stops`);
    return null;
  }
  return stored.assetId;
}

// ---------------------------------------------------------------------------
// Image / Video generation
// ---------------------------------------------------------------------------

export interface ClassroomMediaResult {
  /** Placeholder -> allocated asset id, for each media item stored. */
  assets: Record<string, string>;
  /**
   * The phases the asset store refused for room. Each stopped at its first
   * refusal, and every item of it not yet stored keeps its placeholder.
   */
  storageFull: { images: boolean; video: boolean };
}

/** Generate the media the outlines request and store it for the owner. */
export async function generateMediaForClassroom(
  outlines: SceneOutline[],
  classroomId: string,
  ownerId: string,
): Promise<ClassroomMediaResult> {
  // Collect all media generation requests from outlines
  const requests = outlines.flatMap((o) => o.mediaGenerations ?? []);
  if (requests.length === 0) return { assets: {}, storageFull: { images: false, video: false } };

  // The image and video slots for this job's owner; a slot turned off or
  // unassigned generates nothing of its kind.
  const [imageSlot, videoSlot] = await Promise.all([
    serverMediaConnection('image', ownerId),
    serverMediaConnection('video', ownerId),
  ]);
  const image = imageSlot && imageSlot !== 'off' ? imageSlot : undefined;
  const video = videoSlot && videoSlot !== 'off' ? videoSlot : undefined;

  const mediaMap: Record<string, string> = {};
  const storageFull = { images: false, video: false };

  // Separate image and video requests, generate each type sequentially
  // but run the two types in parallel (providers often have limited concurrency).
  const imageRequests = image ? requests.filter((r) => r.type === 'image') : [];
  const videoRequests = video ? requests.filter((r) => r.type === 'video') : [];

  const generateImages = async () => {
    for (const req of imageRequests) {
      try {
        const providerId = image!.providerId as ImageProviderId;
        const apiKey = image!.apiKey ?? '';
        const providerConfig = IMAGE_PROVIDERS[providerId];
        if (providerConfig?.requiresApiKey && !apiKey) {
          log.warn(`No API key for image provider "${providerId}", skipping ${req.elementId}`);
          continue;
        }
        // The slot's model, else the first catalog model so a provider-only
        // assignment keeps generating. This path is internal (no HTTP response
        // to fail loud with), so the adapter's requireModel must stay a
        // backstop, never the primary failure mode.
        const model = image!.modelId ?? providerConfig?.models?.[0]?.id;

        const result = await generateImage(
          {
            providerId,
            apiKey,
            baseUrl: image!.baseUrl,
            model,
            fetchImpl: image!.managed ? managedMediaProviderFetch : mediaProviderFetch,
          },
          resolveImageSize(
            { prompt: req.prompt, aspectRatio: req.aspectRatio || '16:9' },
            { providerId, modelId: model },
          ),
        );

        let buf: Buffer;
        let mimeType: string;
        if (result.base64) {
          buf = Buffer.from(result.base64, 'base64');
          // The adapter that received these bytes reports their type; the URL
          // branch below reads it off the URL, and this branch has only the
          // adapter's word for it.
          mimeType = storedImageType(result.mimeType);
        } else if (result.url) {
          buf = await downloadToBuffer(result.url);
          if (result.url.startsWith('data:')) {
            mimeType = storedImageType(result.url.slice(5).split(';')[0]?.toLowerCase());
          } else {
            let urlExt = '';
            try {
              urlExt = path.extname(new URL(result.url).pathname);
            } catch {
              urlExt = '';
            }
            mimeType = storedImageType(classroomMediaMimeType(urlExt));
          }
        } else {
          log.warn(`Image generation returned no data for ${req.elementId}`);
          continue;
        }

        const assetId = await storeClassroomAsset(
          ownerId,
          classroomId,
          buf,
          mimeType,
          'image',
          `image ${req.elementId}`,
        );
        if (!assetId) {
          storageFull.images = true;
          break;
        }
        mediaMap[req.elementId] = assetId;
        log.info(`Generated image: ${req.elementId} -> ${assetId}`);
      } catch (err) {
        log.warn(`Image generation failed for ${req.elementId}:`, err);
      }
    }
  };

  const generateVideos = async () => {
    for (const req of videoRequests) {
      try {
        const providerId = video!.providerId as VideoProviderId;
        const apiKey = video!.apiKey ?? '';
        if (!apiKey) {
          log.warn(`No API key for video provider "${providerId}", skipping ${req.elementId}`);
          continue;
        }
        // The slot's model, else the first catalog model (see images above).
        const providerConfig = VIDEO_PROVIDERS[providerId];
        const model = video!.modelId ?? providerConfig?.models?.[0]?.id;

        const normalized = normalizeVideoOptions(providerId, {
          prompt: req.prompt,
          aspectRatio: (req.aspectRatio as '16:9' | '4:3' | '1:1' | '9:16') || '16:9',
        });

        const result = await generateVideo(
          {
            providerId,
            apiKey,
            baseUrl: video!.baseUrl,
            model,
            fetchImpl: video!.managed ? managedMediaProviderFetch : mediaProviderFetch,
            downloadFetchImpl: video!.managed ? managedMediaDownloadFetch : mediaDownloadFetch,
          },
          normalized,
        );

        const buf = await downloadToBuffer(result.url);
        const assetId = await storeClassroomAsset(
          ownerId,
          classroomId,
          buf,
          'video/mp4',
          'video',
          `video ${req.elementId}`,
        );
        if (!assetId) {
          storageFull.video = true;
          break;
        }
        mediaMap[req.elementId] = assetId;
        log.info(`Generated video: ${req.elementId} -> ${assetId}`);
      } catch (err) {
        log.warn(`Video generation failed for ${req.elementId}:`, err);
      }
    }
  };

  await Promise.all([generateImages(), generateVideos()]);

  if (storageFull.images || storageFull.video) {
    log.warn(
      `Asset storage is full: ${requests.length - Object.keys(mediaMap).length} media item(s) keep their placeholder`,
    );
  }
  return { assets: mediaMap, storageFull };
}

// ---------------------------------------------------------------------------
// Placeholder replacement in scene content
// ---------------------------------------------------------------------------

/**
 * Point every slot that holds a generated placeholder at the asset allocated
 * for it, in place. A video repeats its placeholder across `src` and
 * `mediaRef`, and both move together: `mediaRef` is what playback resolves a
 * video through, so leaving it on the placeholder would hide the stored video.
 */
export function replaceMediaPlaceholders(scenes: Scene[], mediaMap: Record<string, string>): void {
  for (const [placeholderRef, assetId] of Object.entries(mediaMap)) {
    for (const scene of scenes) {
      rewriteSceneMediaReference(scene, { placeholderRef, assetId });
    }
  }
}

// ---------------------------------------------------------------------------
// TTS generation
// ---------------------------------------------------------------------------

const DEFAULT_TTS_MIN_INTERVAL_MS = 0;
/** Back-off floor after a rate limit. Independent of `TTS_MIN_INTERVAL_MS`. */
const TTS_RATE_LIMIT_BACKOFF_FLOOR_MS = 1000;
const MAX_TTS_INTERVAL_MS = 15_000;
const MAX_TTS_RATE_LIMIT_RETRIES = 5;
/** Cumulative rate-limit sleep budget for one classroom TTS phase. */
const DEFAULT_TTS_BACKOFF_BUDGET_MS = 120_000;

/** Classroom TTS request spacing. Unset or invalid values fall back to 0. */
function readTtsMinIntervalMs(): number {
  const raw = process.env.TTS_MIN_INTERVAL_MS?.trim();
  if (!raw) return DEFAULT_TTS_MIN_INTERVAL_MS;
  const parsed = Number(raw);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : DEFAULT_TTS_MIN_INTERVAL_MS;
}

/** Total rate-limit back-off budget. Unset or invalid values fall back to 120000ms. `0` disables further waits. */
function readTtsBackoffBudgetMs(): number {
  const raw = process.env.TTS_BACKOFF_BUDGET_MS?.trim();
  if (!raw) return DEFAULT_TTS_BACKOFF_BUDGET_MS;
  const parsed = Number(raw);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : DEFAULT_TTS_BACKOFF_BUDGET_MS;
}

/**
 * Next spacing after a rate limit. A configured interval of 0 must not stay 0:
 * the delay starts at 2× {@link TTS_RATE_LIMIT_BACKOFF_FLOOR_MS} and doubles
 * up to {@link MAX_TTS_INTERVAL_MS}.
 */
function widenTtsSpacing(currentMs: number): number {
  if (currentMs >= MAX_TTS_INTERVAL_MS) return currentMs;
  const base = Math.max(currentMs, TTS_RATE_LIMIT_BACKOFF_FLOOR_MS);
  return Math.min(base * 2, MAX_TTS_INTERVAL_MS);
}

/**
 * Step spacing halfway back toward the configured base.
 * A non-positive success streak leaves spacing unchanged; rate limits reset that streak.
 */
function decayTtsSpacing(currentMs: number, baseMs: number, consecutiveSuccesses: number): number {
  if (consecutiveSuccesses <= 0 || currentMs <= baseMs) return Math.max(currentMs, baseMs);
  return baseMs + Math.floor((currentMs - baseMs) / 2);
}

function isAbortError(error: unknown): boolean {
  return error instanceof Error && error.name === 'AbortError';
}

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new DOMException('Aborted', 'AbortError'));
      return;
    }

    const onAbort = () => {
      clearTimeout(timeoutId);
      reject(new DOMException('Aborted', 'AbortError'));
    };

    const timeoutId = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, ms);

    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

/**
 * Narratable speech clips currently stored on `scenes`.
 * Pass `providerId` to split long lines the same way synthesis does before counting.
 * That split is applied in place so a skipped run and a generated run agree.
 * With no provider there is no length limit, so the stored actions are counted as-is.
 */
export function countNarratableSpeechActions(scenes: Scene[], providerId?: TTSProviderId): number {
  if (providerId) {
    for (const scene of scenes) {
      if (!scene.actions) continue;
      scene.actions = splitLongSpeechActions(scene.actions, providerId);
    }
  }
  let total = 0;
  for (const scene of scenes) {
    for (const action of scene.actions ?? []) {
      if (action.type === 'speech' && (action as SpeechAction).text) total += 1;
    }
  }
  return total;
}

/**
 * TTS was requested but synthesis never started.
 * Coverage stays at zero written clips so the job is not a clean success.
 */
function skippedTtsCoverage(
  scenes: Scene[],
  reason: string,
  providerId?: TTSProviderId,
): ClassroomTtsCoverage {
  const coverage: ClassroomTtsCoverage = {
    written: 0,
    total: countNarratableSpeechActions(scenes, providerId),
  };
  log.warn(reason);
  if (coverage.written < coverage.total)
    log.error(classroomTtsSummary(coverage.written, coverage.total));
  return coverage;
}

export interface ClassroomTtsCoverage {
  written: number;
  total: number;
}

/** A TTS run's coverage, and whether it stopped because the asset store was full. */
export interface ClassroomTtsResult extends ClassroomTtsCoverage {
  storageFull?: true;
}

/** Loud one-line summary for a classroom TTS run. */
export function classroomTtsSummary(written: number, total: number): string {
  const silent = total - written;
  if (silent <= 0) return `TTS generation complete: ${written} clips written`;
  return `TTS generation INCOMPLETE: ${written} written, ${silent} speech actions left silent`;
}

/** Clip counts emitted while classroom TTS is still running. */
export interface ClassroomTtsProgress {
  written: number;
  total: number;
}

/**
 * Synthesize narration for every speech clip.
 * `signal` rejects an in-flight wait when a caller supplies one. The classroom
 * job runner does not supply one.
 * `onProgress` reports clip counts so a long run can refresh job liveness.
 */
export async function generateTTSForClassroom(
  scenes: Scene[],
  classroomId: string,
  ownerId: string,
  signal?: AbortSignal,
  onProgress?: (progress: ClassroomTtsProgress) => void | Promise<void>,
): Promise<ClassroomTtsResult> {
  // The tts slot for this job's owner; browser-native speech is the client's.
  const tts = await serverMediaConnection('tts', ownerId);
  if (!tts || tts === 'off' || tts.providerId === 'browser-native-tts') {
    return skippedTtsCoverage(scenes, 'No server TTS provider configured, skipping TTS generation');
  }

  const providerId = tts.providerId as TTSProviderId;
  const apiKey = tts.apiKey ?? '';
  const ttsProvider = TTS_PROVIDERS[providerId as keyof typeof TTS_PROVIDERS];
  if (ttsProvider?.requiresApiKey && !apiKey) {
    return skippedTtsCoverage(
      scenes,
      `No API key for TTS provider "${providerId}", skipping TTS generation`,
      providerId,
    );
  }
  const ttsBaseUrl = tts.baseUrl || ttsProvider?.defaultBaseUrl;
  const ttsManaged = tts.managed;
  const voice = DEFAULT_TTS_VOICES[providerId as keyof typeof DEFAULT_TTS_VOICES] || 'default';
  const format = ttsProvider?.supportedFormats?.[0] || 'mp3';
  if (providerId === VOXCPM_TTS_PROVIDER_ID && voice === VOXCPM_AUTO_VOICE_ID) {
    return skippedTtsCoverage(
      scenes,
      'VoxCPM Auto Voice requires agent context; skipping server-side TTS generation',
      providerId,
    );
  }

  const baseSpacingMs = readTtsMinIntervalMs();
  let spacingMs = baseSpacingMs;
  let consecutiveSuccesses = 0;
  let lastStartedAt = Number.NEGATIVE_INFINITY;
  // Full delay for the next attempt after a rate limit. Unlike successful-call
  // pacing, this is not reduced by how long the failed request itself took.
  let pendingBackoffMs = 0;
  let backoffSpentMs = 0;
  const backoffBudgetMs = readTtsBackoffBudgetMs();
  let budgetExhausted = false;
  let storageFull = false;
  let written = 0;
  const total = countNarratableSpeechActions(scenes, providerId);

  const waitForTtsSlot = async () => {
    signal?.throwIfAborted();
    const pacingWaitMs = spacingMs - (Date.now() - lastStartedAt);
    const waitMs = pendingBackoffMs > 0 ? pendingBackoffMs : pacingWaitMs;
    pendingBackoffMs = 0;
    if (waitMs > 0) await sleep(waitMs, signal);
    lastStartedAt = Date.now();
  };

  const emitTtsProgress = async () => {
    await onProgress?.({ written, total });
  };

  for (const scene of scenes) {
    if (!scene.actions) continue;

    // Use scene order to make audio IDs unique across scenes
    const sceneOrder = scene.order;

    for (const action of scene.actions) {
      signal?.throwIfAborted();
      if (action.type !== 'speech' || !(action as SpeechAction).text) continue;
      const speechAction = action as SpeechAction;
      // A label for the logs only: the action is stored with the id the pool
      // allocates, the same shape browser generation writes.
      const audioId = `tts_s${sceneOrder}_${action.id}`;
      if (budgetExhausted || storageFull) {
        log.warn(
          `${storageFull ? 'Asset storage is full' : 'TTS back-off budget exhausted'}; leaving ${audioId} silent`,
        );
        await emitTtsProgress();
        continue;
      }
      let rateLimitRetries = 0;

      while (true) {
        await waitForTtsSlot();
        try {
          const result = await generateTTS(
            {
              providerId,
              modelId:
                tts.modelId ??
                (DEFAULT_TTS_MODELS[providerId as keyof typeof DEFAULT_TTS_MODELS] || ''),
              apiKey,
              baseUrl: ttsBaseUrl,
              managed: ttsManaged,
              publicOnly: tts.userEndpoint,
              voice,
              speed: speechAction.speed,
              // The provider's own options (a VoxCPM backend, say).
              providerOptions: adapterOptions(tts),
              signal,
            },
            speechAction.text,
          );

          const assetId = await storeClassroomAsset(
            ownerId,
            classroomId,
            result.audio,
            classroomMediaMimeType(`.${result.format || format}`) ?? 'application/octet-stream',
            'audio',
            `narration ${audioId}`,
          );
          if (!assetId) {
            storageFull = true;
            break;
          }

          speechAction.audioId = assetId;
          written += 1;
          consecutiveSuccesses += 1;
          spacingMs = decayTtsSpacing(spacingMs, baseSpacingMs, consecutiveSuccesses);
          log.info(`Generated TTS: ${audioId} -> ${assetId} (${result.audio.length} bytes)`);
          break;
        } catch (err) {
          if (isAbortError(err) || signal?.aborted) {
            throw isAbortError(err) ? err : new DOMException('Aborted', 'AbortError');
          }
          if (err instanceof TTSRateLimitError && rateLimitRetries < MAX_TTS_RATE_LIMIT_RETRIES) {
            const nextSpacingMs = widenTtsSpacing(spacingMs);
            const retryAfterMs = err.retryAfterMs ?? 0;
            const delayMs = Math.max(nextSpacingMs, retryAfterMs);
            consecutiveSuccesses = 0;
            const remainingBudgetMs = backoffBudgetMs - backoffSpentMs;
            // A single huge Retry-After must not silence every later clip.
            if (retryAfterMs > remainingBudgetMs) {
              spacingMs = nextSpacingMs;
              log.warn(
                `TTS Retry-After ${retryAfterMs}ms exceeds remaining back-off budget for ${audioId}; leaving this clip silent and widening spacing to ${spacingMs}ms`,
              );
              break;
            }
            if (backoffSpentMs + delayMs > backoffBudgetMs) {
              budgetExhausted = true;
              log.warn(
                `TTS back-off budget exhausted for ${audioId}; leaving remaining speech silent`,
              );
              break;
            }
            backoffSpentMs += delayMs;
            rateLimitRetries += 1;
            spacingMs = nextSpacingMs;
            pendingBackoffMs = delayMs;
            log.warn(
              `TTS rate limited for ${audioId}; widening spacing to ${spacingMs}ms (retry ${rateLimitRetries}/${MAX_TTS_RATE_LIMIT_RETRIES})`,
            );
            continue;
          }
          if (err instanceof TTSRateLimitError) {
            log.warn(`TTS rate limit retries exhausted for ${audioId}; leaving speech silent`);
          } else {
            log.warn(`TTS generation failed for action ${action.id}:`, err);
          }
          break;
        }
      }
      await emitTtsProgress();
    }
  }

  const summary = classroomTtsSummary(written, total);
  if (written < total) log.error(summary);
  else log.info(summary);
  return { written, total, ...(storageFull ? { storageFull: true as const } : {}) };
}
