import { AssetQuotaExceededError, type AssetStore } from '@openmaic/storage';
import type { AssetMeta } from '@openmaic/dsl';

import { assetPrincipalForOwner } from '@/lib/persistence/owner-assets';
import { forwardOwnerWrite } from '@/lib/persistence/owner-merges';
import { getServerPersistenceProvider } from '@/lib/persistence/server-provider';

/**
 * The server-side commit half of the asset pool, for bytes a server flow
 * generated.
 *
 * This is the twin of the classic chain's client-side `putAsset`
 * (`lib/media/asset-pool.ts`): bytes go to the pool first, the pool answers
 * with an allocated id, and the document write that names that id is the only
 * "done" signal. Nothing here writes a document and nothing here records a
 * reference — the owner-bound PostgreSQL document store maintains
 * `document_asset_refs` and commits the pending allocation inside the same
 * transaction as the write that names the id (#1473).
 *
 * It exists as one helper rather than as two inline call sites because the
 * refusal branch is the whole point: a store with no room must fail the tool
 * call, not fall back to a second storage model. `lib/server/classroom-media-bytes.ts`
 * remains for the flows that still serve legacy `/api/classroom-media` paths.
 */

/** Which slot of a generated element these bytes are for. Recorded on the entry. */
export type GeneratedAssetKind = 'image' | 'video' | 'poster';

export interface StoreGeneratedAssetInput {
  /**
   * The owner the bytes are allocated for: the owner recorded on the run that
   * generated them. The entry lands in that owner's asset partition and counts
   * against that owner's quota.
   */
  ownerId: string;
  /** The course the bytes belong to. Recorded on the entry's metadata. */
  stageId: string;
  bytes: Uint8Array;
  mimeType: string;
  kind: GeneratedAssetKind;
  /**
   * The store to allocate in. Defaults to this deployment's PostgreSQL asset
   * store. Injected by tests so the refusal branch can be exercised without a
   * database; production callers never pass it.
   */
  assetStore?: AssetStore;
}

export type StoreGeneratedAssetResult =
  | { status: 'stored'; assetId: string }
  | { status: 'refused'; reason: 'storage-full' };

/**
 * A refusal for room, raised where the caller's seam can only return a value.
 *
 * The persist seams of `generate_image` and `generate_video` are typed to
 * return a reference, so a refusal cannot be returned through them. It is
 * thrown instead and classified by the tool, which turns it into a
 * model-visible error with its own reason code — never into a fallback write.
 */
export class AssetStorageFullError extends Error {
  readonly code = 'ASSET_STORAGE_FULL' as const;

  constructor(message = 'The asset store has no room for the generated media.') {
    super(message);
    this.name = 'AssetStorageFullError';
  }
}

/**
 * Whether a store error is the contract's "no room" refusal.
 *
 * Both the class and the declared code are checked, for the same reason the
 * HTTP handler checks both (`@openmaic/storage/server/asset.ts`): a store
 * constructed in another module realm fails `instanceof` while its `code` is
 * still exactly right, and a quota refusal that degraded into an unclassified
 * failure would be reported to the model as a provider error it should retry.
 */
function isStorageFull(error: unknown): boolean {
  if (error instanceof AssetQuotaExceededError) return true;
  if (typeof error !== 'object' || error === null) return false;
  return (error as { code?: unknown }).code === 'ASSET_QUOTA_EXCEEDED';
}

/**
 * Store generated bytes in this deployment's asset pool and return the
 * allocated id.
 *
 * The allocation is PENDING when this resolves: the entry carries a TTL and is
 * committed by the first document write naming the id. A caller that allocates
 * and then fails to write the document leaves an entry the collector reclaims,
 * which is the designed outcome and the reason no reference bookkeeping lives
 * here.
 *
 * Only a refusal for room is a result; every other failure throws, because
 * every other failure is a fault rather than a state the caller can report.
 */
export async function storeGeneratedAsset(
  input: StoreGeneratedAssetInput,
): Promise<StoreGeneratedAssetResult> {
  // The allocation is for whoever owns the run's work now: a claim can move
  // the run's owner to an account while it generates. The forward and the
  // allocation share one transaction under the owner's identity lock, so a
  // claim cannot land between them and leave the entry under a retired owner.
  // `input.assetStore` is a test seam for the refusal branch: it allocates
  // exactly where it is told, unfenced. The production path below is fenced.
  const allocate: (meta: AssetMeta, blob: Blob) => Promise<string> = input.assetStore
    ? (meta, blob) => input.assetStore!.put(assetPrincipalForOwner(input.ownerId), blob, meta)
    : async (meta, blob) => {
        const provider = await getServerPersistenceProvider(process.env.DATABASE_URL ?? '');
        return provider.withTransaction(async (tx) => {
          const ownerId = await forwardOwnerWrite(tx, input.ownerId);
          return provider.assetStoreIn(tx).put(assetPrincipalForOwner(ownerId), blob, meta);
        });
      };
  // `stageId` rides in the entry's metadata rather than in a dedicated column:
  // the browser chain's `putAsset(bytes, meta, { stageId })` never sends its
  // stage to the server at all (it retires a device-local "the store had no
  // room" note), so there is no server-side field to mirror. The durable
  // stage→asset fact is the reference table the document write maintains; this
  // is provenance on the entry itself, for a server-side writer that has no
  // other place to put it.
  const meta = { contentType: input.mimeType, stageId: input.stageId, kind: input.kind };
  // A `Buffer` from a bounded download is a `Uint8Array` over an
  // `ArrayBufferLike`, which `BlobPart` does not admit. This is a view over the
  // same bytes rather than a copy of them: a generated video is up to 200 MiB.
  const part = new Uint8Array(
    input.bytes.buffer as ArrayBuffer,
    input.bytes.byteOffset,
    input.bytes.byteLength,
  );
  try {
    const assetId = await allocate(meta, new Blob([part], { type: input.mimeType }));
    return { status: 'stored', assetId };
  } catch (error) {
    if (isStorageFull(error)) return { status: 'refused', reason: 'storage-full' };
    throw error;
  }
}

/**
 * {@link storeGeneratedAsset} for the persist seams: the id, or
 * {@link AssetStorageFullError}.
 */
export async function storeGeneratedAssetOrThrow(input: StoreGeneratedAssetInput): Promise<string> {
  const stored = await storeGeneratedAsset(input);
  if (stored.status === 'refused') throw new AssetStorageFullError();
  return stored.assetId;
}
