import { HttpAssetStore, HttpDocumentStore } from '@openmaic/storage';
import { HttpRuntimeStore } from '@openmaic/storage/runtime/http';

import {
  assertDocumentStorageConfigurable,
  configureDocumentStorage,
  type DocumentStorageOptions,
} from '@/lib/document-store/config';
import {
  assertAssetPoolStorageConfigurable,
  configureAssetPoolStorage,
  type AssetPoolStorageOptions,
} from '@/lib/media/asset-pool-config';
import { assertRuntimeStorageConfigurable, configureRuntimeStorage } from '@/lib/runtime/config';

/**
 * Where the browser learns its runtime learner key under server persistence.
 *
 * The server derives the key from the request owner (the owner identity seam),
 * and the runtime contract names it in paths and bodies, so the browser has to
 * use exactly that value: any other key is refused with 403
 * FORBIDDEN_LEARNER. The browser therefore asks instead of minting one.
 * Requests carry no credential of their own; the owner cookie rides them.
 */
export const PERSISTENCE_LEARNER_KEY_URL = '/api/persistence/learner-key';

let learnerKeyPromise: Promise<string> | undefined;

export function isBrowserPersistenceEnabled(): boolean {
  return typeof window !== 'undefined' && process.env.NEXT_PUBLIC_PERSISTENCE === '1';
}

async function fetchServerLearnerKey(): Promise<string> {
  const response = await fetch(PERSISTENCE_LEARNER_KEY_URL, {
    method: 'GET',
    credentials: 'same-origin',
    cache: 'no-store',
  });
  if (!response.ok) {
    throw new Error(`Runtime learner key request failed: ${response.status}`);
  }
  const body = (await response.json()) as { learnerKey?: unknown } | null;
  const learnerKey = body?.learnerKey;
  if (typeof learnerKey !== 'string' || learnerKey === '') {
    throw new Error('Runtime learner key response is malformed');
  }
  return learnerKey;
}

/**
 * The server-derived runtime learner key, fetched once per page. A failure is
 * not cached, so a transient error does not pin every later call.
 */
export function getPersistenceLearnerKey(): Promise<string> {
  if (!isBrowserPersistenceEnabled()) {
    return Promise.reject(new Error('Browser persistence is not enabled'));
  }
  return (learnerKeyPromise ??= fetchServerLearnerKey().catch((error) => {
    learnerKeyPromise = undefined;
    throw error;
  }));
}

if (isBrowserPersistenceEnabled()) {
  const runtimeOptions = {
    store: () => new HttpRuntimeStore({ baseUrl: '/api/persistence' }),
    learnerKey: getPersistenceLearnerKey,
  };
  const documentOptions: DocumentStorageOptions = {
    store: ({ validateScene, validateStage }) =>
      new HttpDocumentStore({
        baseUrl: '/api/persistence',
        validateScene,
        validateStage,
      }),
  };
  // The document outlives the browser that produced it, so the media it
  // references must too: generated bytes go to the same endpoint under the
  // same owner, and the document holds the id the pool allocated.
  // `serverBacked` is what tells local-cache cleanup that these refs are not
  // this browser's to delete.
  const assetOptions: AssetPoolStorageOptions = {
    store: () => new HttpAssetStore({ baseUrl: '/api/persistence' }),
    serverBacked: true,
  };
  try {
    // All checks are mutation-free. Once they pass, the synchronous configure
    // calls cannot leave only a subset of the persistence seams configured.
    assertRuntimeStorageConfigurable();
    assertDocumentStorageConfigurable();
    assertAssetPoolStorageConfigurable();
    configureRuntimeStorage(runtimeOptions);
    configureDocumentStorage(documentOptions);
    configureAssetPoolStorage(assetOptions);
  } catch (error) {
    console.error(
      'FATAL: server-backed persistence bootstrap failed; no storage seam changes were applied',
      error,
    );
  }
}
