/**
 * The document view of generated media: which generation placeholders a course
 * still carries, and how one of them is replaced by an allocated asset id.
 *
 * Pure and IO-free over the document, so the browser write-back funnel and the
 * generation runs share one definition of where a generated reference lives. Slots come from the DSL's own slot classification
 * (`slideMediaReferenceSlots`), so a new media-bearing property is picked up
 * here the moment the contract describes it.
 */
import type { Slide } from '@openmaic/dsl';

import { isGeneratedMediaPlaceholder } from '@/lib/media/media-ref';
import { slideMediaReferenceSlots } from '@/lib/media/slide-media-slots';
import type { Scene, Stage } from '@/lib/types/stage';

/** One generated placeholder and the allocated identities that replace it. */
export interface GeneratedMediaReferenceRewrite {
  /** The `gen_img_*` / `gen_vid_*` value the document holds today. */
  readonly placeholderRef: string;
  /** The id the asset pool allocated for the generated bytes. */
  readonly assetId: string;
  /** Allocated id for a generated video poster, when one was stored. */
  readonly posterAssetId?: string;
}

type SlideLike = Pick<Slide, 'background' | 'elements'>;

function slidesOfScene(scene: Scene): SlideLike[] {
  const slides: SlideLike[] = [];
  if (scene.content?.type === 'slide') slides.push(scene.content.canvas);
  for (const whiteboard of scene.whiteboards ?? []) slides.push(whiteboard);
  return slides;
}

/**
 * Replace every occurrence of one placeholder in a slide, in place.
 *
 * A generated video repeats its reference across `src` and `mediaRef`, so all
 * matching slots move together. The poster is written only onto an element
 * this rewrite actually matched, and only when that element has no poster of
 * its own yet — an author-chosen poster is never overwritten by a generated
 * one.
 */
export function rewriteSlideMediaReference(
  slide: SlideLike,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  const slots = [...slideMediaReferenceSlots(slide)];
  const matchedElements = new Set<number>();
  let changed = false;

  for (const slot of slots) {
    if (slot.read() !== rewrite.placeholderRef) continue;
    slot.write(rewrite.assetId);
    changed = true;
    if (slot.elementIndex !== undefined) matchedElements.add(slot.elementIndex);
  }

  if (rewrite.posterAssetId) {
    for (const slot of slots) {
      if (slot.kind !== 'video-poster') continue;
      if (slot.elementIndex === undefined || !matchedElements.has(slot.elementIndex)) continue;
      const current = slot.read();
      if (current && !isGeneratedMediaPlaceholder(current)) continue;
      slot.write(rewrite.posterAssetId);
      changed = true;
    }
  }

  return changed;
}

/** Apply a rewrite to a scene's canvas and whiteboards, in place. */
export function rewriteSceneMediaReference(
  scene: Scene,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  let changed = false;
  for (const slide of slidesOfScene(scene)) {
    if (rewriteSlideMediaReference(slide, rewrite)) changed = true;
  }
  return changed;
}

/** Apply a rewrite to the stage-level whiteboard slides, in place. */
export function rewriteStageMediaReference(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
  rewrite: GeneratedMediaReferenceRewrite,
): boolean {
  let changed = false;
  for (const slide of stage?.whiteboard ?? []) {
    if (rewriteSlideMediaReference(slide, rewrite)) changed = true;
  }
  return changed;
}

/** Every generation placeholder a scene currently carries. */
export function sceneMediaPlaceholders(scene: Scene): Set<string> {
  const refs = new Set<string>();
  for (const slide of slidesOfScene(scene)) {
    for (const slot of slideMediaReferenceSlots(slide)) {
      const ref = slot.read();
      if (ref && isGeneratedMediaPlaceholder(ref)) refs.add(ref);
    }
  }
  return refs;
}

/** Every generation placeholder the stage whiteboard currently carries. */
export function stageMediaPlaceholders(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
): Set<string> {
  const refs = new Set<string>();
  for (const slide of stage?.whiteboard ?? []) {
    for (const slot of slideMediaReferenceSlots(slide)) {
      const ref = slot.read();
      if (ref && isGeneratedMediaPlaceholder(ref)) refs.add(ref);
    }
  }
  return refs;
}

/** Whether a scene still holds this placeholder in any of its media slots. */
export function sceneCarriesMediaReference(scene: Scene, placeholderRef: string): boolean {
  return slidesOfScene(scene).some((slide) =>
    [...slideMediaReferenceSlots(slide)].some((slot) => slot.read() === placeholderRef),
  );
}

/** Whether the stage whiteboard still holds this placeholder. */
export function stageCarriesMediaReference(
  stage: Pick<Stage, 'whiteboard'> | null | undefined,
  placeholderRef: string,
): boolean {
  return (stage?.whiteboard ?? []).some((slide) =>
    [...slideMediaReferenceSlots(slide)].some((slot) => slot.read() === placeholderRef),
  );
}
