/**
 * Media Retry
 *
 * Retries one failed image or video. A course a generation run produces is
 * retried by its run; any other course regenerates the element from this
 * browser, calling /api/generate/image and /api/generate/video, fetching the
 * result blobs and updating the Zustand store.
 *
 * The document outlives this browser, so the bytes go to the asset pool first
 * and the id the pool allocated is written back into the document. Only then
 * is the task done. The local `mediaFiles` table is a device cache (and the
 * keeper of bytes a full store refused), never the source of truth, and
 * "already generated?" is answered by the document instead of by that cache.
 */

import { useMediaGenerationStore } from '@/lib/store/media-generation';
import { requireModelCapabilities } from '@/lib/model-settings/capabilities';
import { mayGenerateForStage } from '@/lib/classroom/generation-permission';
import { db, mediaFileKey, type MediaFileRecord } from '@/lib/device-storage/database';
import type { MediaGenerationRequest } from '@/lib/media/types';
import { commitToPool } from '@/lib/media/commit-to-pool';
import { isRetryableMediaFailure } from '@/lib/media/media-failure';
import {
  MediaReferenceWriteBackError,
  persistGeneratedMediaReference,
  type MediaReferenceWriteBackResult,
} from '@/lib/media/persist-media-reference';
import {
  forgetMediaAllocation,
  pendingMediaAllocation,
  takePendingMediaAllocations,
  type PendingMediaAllocation,
} from '@/lib/media/pending-media-allocations';
import { fetchProxiedMediaUrl } from '@/lib/media/proxy-media-cache';
import { createLogger } from '@/lib/logger';
import { runMediaRetryFor } from '@/lib/generation-run-client/run-media';

const log = createLogger('MediaOrchestrator');

/** Error with a structured errorCode from the API */
class MediaApiError extends Error {
  errorCode?: string;
  constructor(message: string, errorCode?: string) {
    super(message);
    this.errorCode = errorCode;
  }
}

/**
 * A store refusal that still holds the bytes it refused.
 *
 * The bytes are the whole point. They were either just paid for at a provider,
 * or they are the only copy a pre-server-backed course has of its own media --
 * and the failure record written for this element goes to the very row that
 * copy lives in. Carrying them out of the commit is what lets that record keep
 * them, and what lets a later Retry re-attempt the upload instead of the
 * generation.
 */
class MediaStorageRefusalError extends Error {
  constructor(
    override readonly cause: unknown,
    readonly code: string,
    readonly refused: RefusedMediaBytes,
  ) {
    super(cause instanceof Error ? cause.message : String(cause));
    this.name = 'MediaStorageRefusalError';
  }
}

/** Generated bytes an upload refused, kept so nothing has to be bought twice. */
interface RefusedMediaBytes {
  readonly blob: Blob;
  readonly mimeType: string;
  readonly poster?: Blob;
  readonly posterMimeType?: string;
}

/**
 * The structured code a failure should be remembered by, if it has one.
 *
 * A code is what makes a failure permanent: it is written to the local table,
 * survives a reload as a `failed` task, and turns off the Retry affordance. So
 * it is reserved for refusals a retry cannot change — a provider's content
 * decision, a disabled generation setting, and a full asset store.
 *
 * Exactly two error shapes can carry one, and each is named rather than probed
 * for. A generation route's refusal arrives as `MediaApiError`, whose
 * `errorCode` is the route's own; a full store arrives as the
 * `MediaStorageRefusalError` the commit raises from the pool primitive's
 * refusal outcome, whose `code` the primitive already matched against the
 * storage contract. Nothing else reaching this catch classifies a pool write:
 * the primitive owns that test now, so the structural "any object with a
 * `code`" probe this used to end with could no longer be reached by a pool
 * error that was not already wrapped, and a generalization nothing can take is
 * one more shape to keep true. Everything else stays retryable, because
 * everything else might work next time.
 */
function mediaFailureCode(error: unknown): string | undefined {
  if (error instanceof MediaApiError) return error.errorCode;
  if (error instanceof MediaStorageRefusalError) return error.code;
  return undefined;
}

/**
 * Retry a single failed media task.
 */
export async function retryMediaTask(
  elementId: string,
  _target?: { readonly elementId: string; readonly sceneId?: string; readonly slideId?: string },
): Promise<void> {
  // A course a generation run produces: its run generates the element again.
  const runTask = useMediaGenerationStore.getState().getTask(elementId);
  const runRetry = runMediaRetryFor(runTask?.stageId);
  if (runTask && runRetry) {
    if (runTask.status !== 'failed' || !(runTask.retryable ?? isRetryableMediaFailure(runTask))) {
      return;
    }
    useMediaGenerationStore.getState().markPendingForRetry(elementId);
    try {
      await runRetry(elementId);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      log.warn(`Media retry for ${elementId} was refused:`, message);
      useMediaGenerationStore
        .getState()
        .markFailed(elementId, runTask.error ?? message, runTask.errorCode);
    }
    return;
  }
  // Whether the workspace can still generate this kind of media (read first,
  // so the task checked below is the one acted on). Settings that cannot be
  // read leave the task as it is: that is no refusal.
  const capabilities = await requireModelCapabilities();
  if (!capabilities) {
    log.warn(`Media retry for ${elementId} skipped: the model settings could not be read.`);
    return;
  }
  const store = useMediaGenerationStore.getState();
  const task = store.getTask(elementId);
  if (!task || task.status !== 'failed') return;

  // A refusal of the content or the configuration is not retryable, and the
  // affordance that calls this is already hidden for one. Refusing here too
  // keeps the render condition and the action precondition the same rule
  // rather than two that can drift.
  if (!isRetryableMediaFailure(task)) return;

  // The affordance that calls this is already hidden when generation is not
  // permitted; refusing here too is what makes the render condition and the
  // action precondition the same rule rather than two that can drift.
  if (!mayGenerateForStage(task.stageId)) return;

  if (task.type === 'image' && !capabilities.image) {
    store.markFailed(elementId, 'Generation disabled', 'GENERATION_DISABLED');
    return;
  }
  if (task.type === 'video' && !capabilities.video) {
    store.markFailed(elementId, 'Generation disabled', 'GENERATION_DISABLED');
    return;
  }

  // Bytes that reached the pool but whose reference never reached the document.
  //
  // A write-back that fails with the allocation retained parks it, and nothing
  // is written to the local media table, because that write only happens after
  // a successful write-back. So the bytes are in the pool, the document still
  // carries the placeholder, and this browser holds no cached copy -- a Retry
  // that went to the provider from here would pay for the media a second time
  // and allocate a second asset for bytes the pool already has, with the first
  // one left for server-side reclamation.
  const parked = pendingMediaAllocation(task.stageId, elementId);
  if (parked) {
    useMediaGenerationStore.getState().markPendingForRetry(elementId);
    let outcome: MediaReferenceWriteBackResult;
    try {
      outcome = await persistGeneratedMediaReference(parked);
    } catch (error) {
      // Still parked, still retryable, and still no provider call: the next
      // Retry comes back through here.
      const message = error instanceof Error ? error.message : String(error);
      log.warn(`Write-back retry failed for ${elementId}:`, message);
      useMediaGenerationStore.getState().markFailed(elementId, message);
      return;
    }
    // The object URL is minted by the commit that parked this, so it is present
    // in practice; an allocation without one degrades to resolving the
    // allocated id through the asset lease, which is what a fresh browser does.
    const objectUrl = parked.objectUrl ?? '';
    if (outcome === 'held') {
      // The slide this belongs to still has not been built. The allocation
      // stays parked and the task stays keyed by the placeholder the document
      // carries, so the request reads as answered and nothing asks again.
      useMediaGenerationStore.getState().markDone(elementId, objectUrl, parked.posterObjectUrl);
      return;
    }
    // Placed. Taking the entry is what keeps a later rewrite of an
    // already-rewritten slot from looking possible; the non-draining record
    // stays, because a snapshot captured before this rewrite still has to be
    // corrected at the write boundary.
    takePendingMediaAllocations(task.stageId, [elementId]);
    useMediaGenerationStore
      .getState()
      .rekeyDone(
        elementId,
        parked.assetId,
        objectUrl,
        parked.posterObjectUrl,
        parked.posterAssetId,
      );
    return;
  }

  // Bytes this browser already holds for the element, whatever put them there:
  // a store that refused the upload and kept them, or a course generated before
  // this application stored media server-side. A retry adopts them because
  // they are paid for, so it re-attempts the upload
  // rather than buying the media again. The condition is the bytes, not the
  // error code: an upload refused for room and then retried into a network
  // failure has lost its code but not its bytes, and asking a provider for them
  // a third time would be the second thing that costs money for nothing.
  //
  // Read BEFORE anything is removed, and the row is NOT removed first: it is
  // the only copy until an upload succeeds.
  const dbKey = mediaFileKey(task.stageId, elementId);
  const refused = await refusedMediaBytes(task.stageId, elementId, task.type);
  if (!refused) {
    // Nothing to keep. Clearing the persisted failure is what lets a fresh
    // result be written under this key.
    await db.mediaFiles.delete(dbKey).catch(() => {});
  }

  // Re-read after the await: only a still-failed task may be retried, and the
  // check has to come BEFORE the state is destroyed. Marking first and refusing
  // afterwards is what turned a recoverable failure into a slide stuck at
  // `pending` with no affordance left to recover it.
  if (useMediaGenerationStore.getState().getTask(elementId)?.status !== 'failed') return;
  useMediaGenerationStore.getState().markPendingForRetry(elementId);
  const committed = await generateSingleMedia(
    {
      type: task.type,
      prompt: task.prompt,
      elementId: task.elementId,
      aspectRatio: task.params.aspectRatio as MediaGenerationRequest['aspectRatio'],
      style: task.params.style,
    },
    task.stageId,
    refused,
  );

  // The retry landed. Its bytes live under the allocated id now, so the row
  // kept under the placeholder is a stale duplicate carrying a failure that no
  // longer happened. Read from what the attempt reported, never from the task
  // table: a course switch clears that table, and reading "no failed task" as
  // "it worked" is how the only copy of the bytes gets deleted after a refusal.
  if (refused && committed) {
    await db.mediaFiles.delete(dbKey).catch(() => {});
  }
}

/**
 * The bytes kept for an element a full store refused.
 *
 * The row is the one the failure record was written around, so it carries the
 * error that was recorded alongside the media -- read it anyway, since here the
 * error is what identifies it.
 */
async function refusedMediaBytes(
  stageId: string,
  elementId: string,
  type: MediaGenerationRequest['type'],
): Promise<RefusedMediaBytes | undefined> {
  const row = await db.mediaFiles.get(mediaFileKey(stageId, elementId)).catch(() => undefined);
  if (!row?.blob || row.blob.size === 0) return undefined;
  const poster = row.poster && row.poster.size > 0 ? row.poster : undefined;
  return {
    blob: row.blob,
    mimeType: storedMediaType(row.blob, type === 'video' ? 'video/mp4' : 'image/png'),
    ...(poster ? { poster, posterMimeType: storedMediaType(poster, 'image/jpeg') } : {}),
  };
}

/** Build the renderer retry scope while classic retries remain placeholder-keyed. */
export function mediaRetryTarget(
  elementId: string,
  sceneId: string | undefined,
  sceneData: unknown,
): { elementId: string; sceneId?: string; slideId?: string } {
  const slideId =
    sceneData && typeof sceneData === 'object' && 'canvas' in sceneData
      ? (sceneData as { canvas?: { id?: string } }).canvas?.id
      : undefined;
  return { elementId, ...(sceneId ? { sceneId } : {}), ...(slideId ? { slideId } : {}) };
}

// ==================== Internal ====================

/** What the generated-media write-back leaves behind for the task to read. */
interface GeneratedMediaPlacement {
  readonly result: MediaReferenceWriteBackResult;
  readonly objectUrl: string;
  readonly posterObjectUrl?: string;
  readonly posterAssetId?: string;
}

/**
 * Allocate a video's poster, and never let it cost the video.
 *
 * A poster is decorative: it is written only into a slot that has none of its
 * own. Letting its upload fail the commit would discard a stored video and send
 * the retry to submit the most expensive job in the system a second time, so a
 * poster failure costs the poster and nothing else.
 *
 * It goes through the same primitive as everything else this browser puts in
 * the pool, with both later steps empty, because a poster is a bare allocation:
 * it holds no reference of its own in the document (it rides in the slot its
 * video fills) and no row of its own in the cache (it rides in its video's
 * row). It retains nothing on a refusal for the same reason — there is no key a
 * later attempt would look for it under, and its video's row already carries
 * the bytes.
 */
async function allocatePoster(args: {
  elementId: string;
  stageId: string;
  posterBlob: Blob;
  posterMimeType?: string;
}): Promise<string | undefined> {
  const outcome = await commitToPool<void>({
    slot: args.elementId,
    bytes: args.posterBlob,
    mimeType: args.posterMimeType ?? args.posterBlob.type,
    writeBack: async () => undefined,
    mirror: async () => undefined,
  });
  if (outcome.status === 'stored') return outcome.assetId;
  log.warn(`Poster allocation failed for ${args.elementId}; keeping the video:`, outcome.error);
  return undefined;
}

/**
 * Commit generated bytes under server-backed persistence: pool first, then the
 * document, then the local cache, and only then the task.
 *
 * Order is the contract, and it is `commitToPool` that holds it now. A
 * reference reaches the document only after `put` returned an id, so the
 * document can never name bytes that were not stored; and a failure anywhere
 * before the write-back leaves the placeholder in place with the provider
 * called exactly once, so the retry happens on the next owner load rather than
 * inside this run.
 *
 * The refusal this path wants is the primitive's `refused-retained`, translated
 * back into the error that carries the bytes to the failure record
 * `generateSingleMedia` writes around them. That record is where this caller's
 * retention lives: the row holds the refusal's message and code alongside the
 * bytes, and only the catch that sees the failure knows those — which is why no
 * `retain` sink is handed to the primitive here.
 */
async function commitPooledMedia(args: {
  req: MediaGenerationRequest;
  stageId: string;
  paramsJson: string;
  blob: Blob;
  mimeType: string;
  posterBlob?: Blob;
  posterMimeType?: string;
}): Promise<void> {
  const { req, stageId, paramsJson, blob, mimeType, posterBlob, posterMimeType } = args;

  const outcome = await commitToPool<GeneratedMediaPlacement>({
    slot: req.elementId,
    bytes: blob,
    mimeType,
    writeBack: async (assetId) => {
      const posterAssetId = posterBlob
        ? await allocatePoster({
            elementId: req.elementId,
            stageId,
            posterBlob,
            ...(posterMimeType ? { posterMimeType } : {}),
          })
        : undefined;

      // Minted before the write-back, not after it, so the allocation the
      // funnel may park in the same turn as its decision is complete: an entry
      // drained a microtask later must carry the bytes this tab can already
      // render.
      const objectUrl = URL.createObjectURL(blob);
      const posterObjectUrl = posterBlob ? URL.createObjectURL(posterBlob) : undefined;
      const allocation: PendingMediaAllocation = {
        stageId,
        placeholderRef: req.elementId,
        assetId,
        posterAssetId,
        objectUrl,
        posterObjectUrl,
      };

      try {
        const result = await persistGeneratedMediaReference(allocation);
        return { result, objectUrl, posterObjectUrl, posterAssetId };
      } catch (error) {
        // The funnel places or parks the allocation whenever the ids could be
        // referenced, and says so. Reclaiming is for the one case where nothing
        // can possibly hold them — otherwise a lost response would take an
        // asset the persisted document already names.
        if (error instanceof MediaReferenceWriteBackError && error.allocationRetained) throw error;
        URL.revokeObjectURL(objectUrl);
        if (posterObjectUrl) URL.revokeObjectURL(posterObjectUrl);
        // Forgetting is all a browser does here. The record outlives the parked
        // queue, so leaving it behind would let a later save stamp an id whose
        // bytes nothing references — and the placeholder it replaced would be
        // gone with it, which reads as "already generated" and stops any retry.
        //
        // The bytes themselves are NOT deleted. Asset deletion is refused to
        // every browser, because the principal it scopes to is shared and would
        // let any caller destroy another author's media. The entry does not
        // need a browser to release it: no document write ever commits this
        // allocation, so it stays pending and the collector's entry pass takes
        // it once ASSET_PENDING_TTL_MS has elapsed.
        forgetMediaAllocation(stageId, req.elementId);
        throw error;
      }
    },
    // Local cache for this tab only. The document already points at the pool,
    // so a failed cache write costs a re-download, never the media.
    mirror: async (assetId) => {
      await db.mediaFiles
        .put({
          id: mediaFileKey(stageId, assetId),
          stageId,
          type: req.type,
          blob,
          mimeType,
          size: blob.size,
          poster: posterBlob,
          placeholderRef: req.elementId,
          prompt: req.prompt,
          params: paramsJson,
          createdAt: Date.now(),
        })
        .catch((error: unknown) => {
          log.warn(`Local media cache write failed for ${assetId}:`, error);
        });
    },
  });

  if (outcome.status === 'refused-retained') {
    // A full store keeps its bytes: they leave through the error so the failure
    // record is written around them rather than over them.
    throw new MediaStorageRefusalError(outcome.error, outcome.code, {
      blob,
      mimeType,
      ...(posterBlob ? { poster: posterBlob } : {}),
      ...(posterBlob && posterMimeType ? { posterMimeType } : {}),
    });
  }
  // Everything else is an ordinary failure and is retried from the provider, as
  // it always was.
  if (outcome.status === 'failed') throw outcome.error;

  const { result, objectUrl, posterObjectUrl, posterAssetId } = outcome.placement;
  if (result === 'held') {
    // The slide this media belongs to has not been built yet. The funnel holds
    // the allocation; the task stays keyed by the placeholder the document
    // still carries, so the request reads as answered and the provider is not
    // asked a second time.
    useMediaGenerationStore.getState().markDone(req.elementId, objectUrl, posterObjectUrl);
    return;
  }

  useMediaGenerationStore
    .getState()
    .rekeyDone(req.elementId, outcome.assetId, objectUrl, posterObjectUrl, posterAssetId);
}

/**
 * The locally cached bytes for a placeholder, under either key this
 * application has used for them.
 *
 * A course generated before server-backed storage has its row under the
 * placeholder itself (`${stageId}:gen_img_3`), because that was the only id
 * there was. A course generated after it has the same bytes under the
 * allocated id (`${stageId}:ast_…`), with the placeholder it replaced recorded
 * in `placeholderRef`. Both are "bytes this browser already paid for", and a
 * document that carries the placeholder again — a rollback, a restored backup,
 * an edit that reinstated an outline — must be able to adopt either. Looking
 * only under the placeholder key was enough for the first layout and silently
 * regenerated the second.
 *
 * A row that records only a hosted URL (`ossKey`) and no bytes is treated as
 * absent: that URL is the provider's address, not something a document may
 * hold. A row recording a permanent failure is absent too — it is a refusal,
 * not media.
 */
async function adoptableCachedMedia(
  stageId: string,
  placeholderRef: string,
): Promise<{ blob: Blob; poster?: Blob } | undefined> {
  const usable = (row: MediaFileRecord | undefined): { blob: Blob; poster?: Blob } | undefined => {
    if (!row || row.error || !row.blob || row.blob.size === 0) return undefined;
    return { blob: row.blob, ...(row.poster ? { poster: row.poster } : {}) };
  };

  const direct = usable(
    await db.mediaFiles.get(mediaFileKey(stageId, placeholderRef)).catch(() => undefined),
  );
  if (direct) return direct;

  // `placeholderRef` is not indexed, so the fallback is a stage-scoped scan.
  const candidates = (await loadCachedMediaByPlaceholder(stageId)).get(placeholderRef) ?? [];
  for (const row of candidates) {
    const adoptable = usable(row);
    if (adoptable) return adoptable;
  }
  return undefined;
}

async function loadCachedMediaByPlaceholder(
  stageId: string,
): Promise<Map<string, MediaFileRecord[]>> {
  const rows = await db.mediaFiles
    .where('stageId')
    .equals(stageId)
    .toArray()
    .catch(() => [] as MediaFileRecord[]);
  const index = new Map<string, MediaFileRecord[]>();
  for (const row of rows) {
    if (!row.placeholderRef) continue;
    const existing = index.get(row.placeholderRef);
    if (existing) existing.push(row);
    else index.set(row.placeholderRef, [row]);
  }
  // Newest first. A regenerated element forks to a fresh id and its
  // predecessor's row is retained, so several rows can name the same
  // placeholder; adopting whichever one the index happened to return first
  // would restore the superseded image.
  for (const candidates of index.values()) {
    candidates.sort((left, right) => (right.createdAt ?? 0) - (left.createdAt ?? 0));
  }
  return index;
}

/**
 * Adopt bytes this browser already holds for a placeholder, without asking a
 * provider for them again.
 *
 * The local media table is keyed by `stageId:ref`, and bytes a full store
 * refused are kept there under the very placeholder the document still names.
 * Committing them through the ordinary path stores them in the pool and writes
 * the allocated id back, so the course converges on the author's next load at
 * no cost — and a visitor, who has no such table, simply sees the media once
 * the author has been through.
 *
 * A row that records only a hosted URL (`ossKey`) and no bytes is treated as
 * absent: that URL is the provider's address, not something a document may
 * hold, and re-downloading it is not obviously cheaper or more reliable than
 * regenerating. Returns whether the element is finished.
 */
async function commitCachedMedia(
  req: MediaGenerationRequest,
  stageId: string,
  paramsJson: string,
): Promise<boolean> {
  const cached = await adoptableCachedMedia(stageId, req.elementId);
  const blob = cached?.blob;
  if (!cached || !blob || blob.size === 0) return false;

  const poster = cached.poster && cached.poster.size > 0 ? cached.poster : undefined;
  log.info(`Adopting locally cached bytes for ${req.elementId}; no provider call.`);
  await commitPooledMedia({
    req,
    stageId,
    paramsJson,
    blob,
    mimeType: storedMediaType(blob, req.type === 'video' ? 'video/mp4' : 'image/png'),
    posterBlob: poster,
    ...(poster ? { posterMimeType: storedMediaType(poster, 'image/jpeg') } : {}),
  });
  return true;
}

/**
 * The content type to record for stored bytes.
 *
 * The generation routes declare no media type, so the only signal is whatever
 * the transfer reported. A generic or empty value carries no information and
 * must not become the asset's recorded type: the pool mints its object URL from
 * it, and `<video>` will not play a source it is told is an octet stream.
 */
function storedMediaType(blob: Blob, fallback: string): string {
  const declared = blob.type.trim();
  return declared && declared !== 'application/octet-stream' ? declared : fallback;
}

/**
 * Generate (or re-store) one element, and say whether its bytes reached the
 * store and the element is finished.
 *
 * The retry deletes the row that was holding the only copy of the bytes only
 * when this says so, because the obvious substitute -- "the task is no longer
 * failed" -- is a fact about a table a course switch clears out from under it.
 *
 * `refusedBytes` short-circuits the provider entirely: it is what a Retry hands
 * back after a full store kept the bytes, so the retry re-attempts the upload
 * rather than buying the media a second time.
 */
async function generateSingleMedia(
  req: MediaGenerationRequest,
  stageId: string,
  refusedBytes?: RefusedMediaBytes,
): Promise<boolean> {
  const store = useMediaGenerationStore.getState();
  store.markGenerating(req.elementId);

  try {
    const paramsJson = JSON.stringify({
      aspectRatio: req.aspectRatio,
      style: req.style,
    });

    if (refusedBytes) {
      await commitPooledMedia({
        req,
        stageId,
        paramsJson,
        blob: refusedBytes.blob,
        mimeType: refusedBytes.mimeType,
        ...(refusedBytes.poster ? { posterBlob: refusedBytes.poster } : {}),
        ...(refusedBytes.posterMimeType ? { posterMimeType: refusedBytes.posterMimeType } : {}),
      });
      return true;
    }

    // Bytes this browser already holds for the placeholder (a store that
    // refused them earlier kept them) are already paid for, so they are
    // committed instead of bought again.
    if (await commitCachedMedia(req, stageId, paramsJson)) {
      return true;
    }

    if (req.type === 'image') {
      const result = await callImageApi(req, stageId);
      // A hosted URL is the provider's address, not a durable reference the
      // document may hold, so the bytes are fetched and put to the pool.
      const blob = await fetchAsBlob(result.ossUrl || result.url);
      await commitPooledMedia({
        req,
        stageId,
        paramsJson,
        blob,
        mimeType: storedMediaType(blob, 'image/png'),
      });
      return true;
    }
    const result = await callVideoApi(req);
    const blob = await fetchAsBlob(result.ossUrl || result.url);
    const posterSource = result.posterOssUrl || result.poster;
    const posterBlob = posterSource
      ? await fetchAsBlob(posterSource).catch(() => undefined)
      : undefined;
    await commitPooledMedia({
      req,
      stageId,
      paramsJson,
      blob,
      mimeType: storedMediaType(blob, 'video/mp4'),
      posterBlob,
      ...(posterBlob ? { posterMimeType: storedMediaType(posterBlob, 'image/jpeg') } : {}),
    });
    return true;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const errorCode = mediaFailureCode(err);
    log.error(`Failed ${req.elementId}:`, message);
    useMediaGenerationStore.getState().markFailed(req.elementId, message, errorCode);

    // Bytes a full store refused. They are kept, and the record below is
    // written around them rather than over them: for a course being converted
    // from local storage this row IS the only copy of its media, and for a
    // freshly generated element these are bytes already paid for. Either way a
    // Retry after the ceiling is raised re-attempts the upload and calls no
    // provider.
    // A retry that was handed bytes still holds them when it fails for some
    // other reason -- a dropped connection, a 500 -- and that failure must not
    // be the thing that finally throws them away.
    const refused =
      err instanceof MediaStorageRefusalError ? err.refused : (refusedBytes ?? undefined);

    // Persist the failure so it survives a page refresh: a restored task
    // carrying an error is a `failed` task, and nothing re-runs one unasked. A
    // failure with bytes to keep is recorded for that reason alone, so the row
    // that holds them survives too.
    if (errorCode || refused) {
      await db.mediaFiles
        .put({
          id: mediaFileKey(stageId, req.elementId),
          stageId,
          type: req.type,
          blob: refused?.blob ?? new Blob(),
          mimeType: refused?.mimeType ?? (req.type === 'image' ? 'image/png' : 'video/mp4'),
          size: refused?.blob.size ?? 0,
          ...(refused?.poster ? { poster: refused.poster } : {}),
          placeholderRef: req.elementId,
          prompt: req.prompt,
          params: JSON.stringify({ aspectRatio: req.aspectRatio, style: req.style }),
          error: message,
          errorCode,
          createdAt: Date.now(),
        })
        .catch(() => {}); // best-effort
    }
    return false;
  }
}

async function callImageApi(
  req: MediaGenerationRequest,
  stageId: string,
): Promise<{ url: string; ossUrl?: string }> {
  // The image slot names the provider and model on the server.
  const response = await fetch('/api/generate/image', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      prompt: req.prompt,
      aspectRatio: req.aspectRatio,
      style: req.style,
      stageId,
    }),
  });

  if (!response.ok) {
    const data = await response.json().catch(() => ({}));
    throw new MediaApiError(data.error || `Image API returned ${response.status}`, data.errorCode);
  }

  const data = await response.json();
  if (!data.success)
    throw new MediaApiError(data.error || 'Image generation failed', data.errorCode);

  // Result may have ossUrl (CDN direct), url, or base64
  const ossUrl = data.result?.ossUrl as string | undefined;
  // A provider that answers with inline bytes reports what they are; a bare
  // `base64` from a provider that does not keeps the PNG assumed here.
  const inlineMime = (data.result?.mimeType as string | undefined) || 'image/png';
  const url =
    data.result?.url ||
    (data.result?.base64 ? `data:${inlineMime};base64,${data.result.base64}` : '');
  if (!ossUrl && !url) throw new Error('No image URL in response');
  return { url, ossUrl };
}

async function callVideoApi(req: MediaGenerationRequest): Promise<{
  url: string;
  poster?: string;
  ossUrl?: string;
  posterOssUrl?: string;
  width?: number;
  height?: number;
  duration?: number;
}> {
  // The video slot names the provider and model on the server.
  const response = await fetch('/api/generate/video', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      prompt: req.prompt,
      aspectRatio: req.aspectRatio,
    }),
  });

  if (!response.ok) {
    const data = await response.json().catch(() => ({}));
    throw new MediaApiError(data.error || `Video API returned ${response.status}`, data.errorCode);
  }

  const data = await response.json();
  if (!data.success)
    throw new MediaApiError(data.error || 'Video generation failed', data.errorCode);

  const url = data.result?.url;
  if (!url) throw new Error('No video URL in response');
  return {
    url,
    poster: data.result?.poster,
    ossUrl: data.result?.ossUrl,
    posterOssUrl: data.result?.posterOssUrl,
    width: data.result?.width,
    height: data.result?.height,
    duration: data.result?.duration,
  };
}

async function fetchAsBlob(url: string): Promise<Blob> {
  // For data URLs, convert directly
  if (url.startsWith('data:')) {
    const res = await fetch(url);
    return res.blob();
  }
  // For remote URLs, proxy through our server to bypass CORS restrictions.
  // Routed through the shared proxy-media negative cache so a permanently
  // failed URL (4xx) is not re-fetched by later retries.
  //
  // Deliberately unabortable. The provider call that produced this URL has
  // already been billed, so cancelling the download throws away work that is
  // paid for — and the shared proxy cache would record the cancellation as a
  // transient failure against the URL, which after three aborts blocks it for
  // every consumer in the session. Letting the download finish costs a few
  // seconds after a Stop; cancelling it costs the image.
  if (url.startsWith('http://') || url.startsWith('https://')) {
    const res = await fetchProxiedMediaUrl(url);
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.error || `Proxy fetch failed: ${res.status}`);
    }
    return res.blob();
  }
  // Relative URLs (shouldn't happen, but handle gracefully)
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch blob: ${res.status}`);
  return res.blob();
}
